//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorPanel2018v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Rooms
    {
        public int Link_ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
        public virtual Booking_Rooms Booking_Rooms1 { get; set; }
        public virtual Booking_Rooms Booking_Rooms2 { get; set; }
    }
}
