//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorPanel2018v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Booking_Rooms = new HashSet<Booking_Rooms>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> Numberofpeople { get; set; }
        public Nullable<System.DateTime> Arrival_date { get; set; }
        public Nullable<System.DateTime> Departure_date { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Rooms> Booking_Rooms { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
