//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorPanel2018v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomFacility()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int FacilityID { get; set; }
        public Nullable<bool> AirCon { get; set; }
        public Nullable<bool> Tv { get; set; }
        public Nullable<bool> Telephone { get; set; }
        public Nullable<bool> Balcony { get; set; }
        public Nullable<bool> Parking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
